### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by johnpancoast** [oct8cat/sublime-phpdox#5]
```
<?php

class Test {
    public function hello()
    {
        echo 'Hello';
    }
}
```
- Go to class line and hit F5.
- Get following error.

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./PhpDox.py", line 68, in run
  File "./PhpDox.py", line 79, in process_line
TypeError: 'NoneType' object is unsubscriptabl

**Comment by johnpancoast** [comment]
Nvmnd. Closing sublime and reopening appeared to fix it.
